### ISSUE TITLE
Not opening full grid if size is smaller than default

### ISSUE THREAD

**Issue by zachOS-tech** [brollin/flex-mouse-grid#9]
# Problem
When I use `grid smaller`, and reopen the grid, it is not taking up the entire space on my screen. It appears that it takes up the amount of rows and columns it would need to fill the screen on the default layout ('im' is at the bottom right of my screen for the default layout).

I've included a video below showing that if I start with it smaller, increase the size(back to default), and then go back to it smaller, it fixes the issue. But if I close the grid and reopen it it has the issue again. I also showed at the end of the video, that if I close the grid with the default size, it doesn't have the issue when I reopen the grid.

# Demo
https://github.com/user-attachments/assets/fda22b51-6b4f-4448-be67-824f050b37c1

# Environment
OS: Windows 11
Talon Version: 0.4.0
.talon/user plugins:
- community
- cursorless-settings
- cursorless-talon
- flex-mouse-grid

**Comment by brollin** [comment]
Thanks for the great bug report. I'm able to reproduce. Hopefully I will have a fix for you later today.

**Comment by brollin** [comment]
Ok should be fixed by https://github.com/brollin/flex-mouse-grid/commit/8dbb539202f46004dcb507e3f61a0375e164c768 . Thanks again!

**Comment by zachOS-tech** [comment]
Thanks for the extremely quick turnaround time! I can confirm it's working on my computer as well.

Thanks for the great work you're doing with this.

**Comment by brollin** [comment]
🙏 my pleasure!
